### ISSUE TITLE
Errors when compiling ATTPCROOT

### ISSUE THREAD

**Issue by tanahn** [ATTPC/ATTPCROOTv2#143] opened 2022-08-03 20:08 UTC
I have previously compiled ATTPCROOT on our cluster, but fail to compile a version I downloaded on July 20, 2022.

I am using GCC 10.2.0 and the output from cmake and make are attached.

[cmake_output.txt](https://github.com/ATTPC/ATTPCROOTv2/files/9254633/cmake_output.txt)

[make_output.txt](https://github.com/ATTPC/ATTPCROOTv2/files/9254639/make_output.txt)

[CMakeCache.txt](https://github.com/ATTPC/ATTPCROOTv2/files/9254640/CMakeCache.txt)

**Comment by anthoak13** [comment] 2022-08-04 01:02
Do you remember what was the version you had previously that compiled? I want to take a look to see if I can narrow down what changed build system wise between then and now. And if that version is still on the cluster, does it still build?

Can you also run `ldd --version`? There are some bug reports floating around about the missing `xlocal.h` include that I suspect is the actually root cause of the error and GLIBC version people are running (https://bugs.llvm.org/show_bug.cgi?id=37596).

**Comment by anthoak13** [comment] 2022-08-04 01:04
This is also unrelated to the current problem, but can you post the cmake output with this line uncommented(https://github.com/ATTPC/ATTPCROOTv2/blob/b04941773b6a858282650f9f6800f3b703dca6dc/CMakeLists.txt#L70)?

In your logs I noticed some developer errors on the hdf5 search which shouldn't be there (also probably related to why you had to do so much fiddling around with hdf5 libraries in the first place)

**Comment by tanahn** [comment] 2022-08-04 20:29
I tried to build the older version that was successfully built before, and I get the same error. So previous version does not build.

The output from ldd --version: 

ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

Another fact, I confirmed that between the last successful build and when I downloaded the current version on our cluster, there was an OS upgrade on our cluster front-end machines. This seems to be in line with the headers having been changed.

So is there a recommended way to fix this problem? Would I have to recompile ROOT or FairSoft altogether?

git log for the current version I have:
commit f5e1f7e199d595b9cd2118392bedcc323c9f2283 


git log for previous version: commit 27dbf7c268bfdd422f774760d8829076b930bd09

**Comment by anthoak13** [comment] 2022-08-04 20:36
That definitely sounds like ROOT's copying of header files is to blame. I think you will have to recompile ROOT at the very least. I'm hopeful FairRoot/the rest of fair soft will not need to be rebuilt but I'm not sure about that.

**Comment by tanahn** [comment] 2022-08-04 20:37
Here is the output with the relevant line commented out of CMakeLists.txt.
[cmake_output_2.txt](https://github.com/ATTPC/ATTPCROOTv2/files/9263180/cmake_output_2.txt)

**Comment by tanahn** [comment] 2022-08-04 20:38
Ok, I will try to recompile ROOT and report back.

**Comment by tanahn** [comment] 2022-08-16 16:58
I was successfully able to recompile FairSoft and then proceeded to recompile ATTPCROOT. I have not recompiled FairRoot at the moment. It looks like a good amount of the code is compiling successfully, so the recompilation of ROOT seems to have solved the initial problem, but I run into another compilation problem below:

AtUnpack/CMakeFiles/AtUnpack.dir/build.make:387: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1345: AtUnpack/CMakeFiles/AtUnpack.dir/all] Error 2

Perhaps this is a make/cmake issue?

**Comment by anthoak13** [comment] 2022-08-16 17:00
Can you copy over the lines around AtUnpack/CMakeFiles/AtUnpack.dir/build.make:387?

I've never seen an error like this before that seems to be thrown by the make file generated by cmake.

**Comment by tanahn** [comment] 2022-08-16 17:36
So here is that line and one before and after it:

lib/libAtUnpack.so.0.3.0: lib/libAtData.so.0.3.0
lib/libAtUnpack.so.0.3.0: hdf5::hdf5-shared-NOTFOUND
lib/libAtUnpack.so.0.3.0: /afs/crc/group/nsl/activetarget/software/attpc_root/FairSoft/install/lib/libVMCLibrary.so

This seems to be (or related to) the previous issue on the HDF5 libraries not being correctly found/specified. I will try to specify where the library is again.

**Comment by tanahn** [comment] 2022-08-16 18:04
I did have trouble with the HDF5 library that was installed on our cluster during my compile back in April, so I downloaded and compiled my own version, which eventually worked. I don't know if that is helpful.

**Comment by tanahn** [comment] 2022-08-16 18:14
Ok, I found some old notes where I solved the hdf5 problem with the cmake flag:

-DHDF5_DIR=/afs/crc/group/nsl/activetarget/software/attpc_root/hdf5-1.10.4/config/cmake/scripts

This seems to have set the HDF5_DIR variable correctly. I was incorrectly using the install directory. I must admit, I don't know how I figured this out previously.

This was the reason I compiled my own version, because our cluster version didn't have a config directory.

**Comment by anthoak13** [comment] 2022-08-16 18:16
Okay, that tracks because we try to use the targets exported by the config script of it can be found. Do you get the same error when the config directory is set this way?

**Comment by tanahn** [comment] 2022-08-16 18:24
I don't know if I understand your question about the "config directory is set this way"? Do you mean if I do not specify the -DHDF5_DIR flag the right way?

When I run cmake with the flag above, there is no longer the message that -- hdf5 library in use: hdf5::hdf5-shared-NOTFOUND and the HDF5_DIR is set to /afs/crc/group/nsl/activetarget/software/attpc_root/hdf5-1.10.4/install/share/cmake/hdf5.

Then the compilation finishes successfully.

**Comment by anthoak13** [comment] 2022-08-18 01:20
By "config directory is set this way" I meant just using the `-DHDF5_DIR` flag when running cmake. It sounds like it's working now, so I will close the issue.

**Closed by anthoak13** 2022-08-18 01:20 UTC
